zombocom/rack-timeout

- rack-timeout.gemspec
Allows developers to to `bundle open rack-timeout` after a `bundle update` to see what's new etc.
> Include CHANGELOG in gem

- lib/rack/timeout/rails.rb
…, but after Rack::Lock, which caused issues, and after all the static file stuff, which kinda makes sense.
> change rails initialization to insert our middleware before Rack::Runtime

- CHANGELOG
- README.markdown
- lib/rack/timeout/base.rb
- lib/rack/timeout/logger.rb
- lib/rack/timeout/logging-observer.rb
Basically makes customizing logging options a lot simpler. No need to expose StateChangeLoggingObserver details.
> Rack::Timeout::Logger and related changes

- CHANGELOG
- lib/rack/timeout/core.rb
- lib/rack/timeout/rollbar.rb
Usage: after requiring rollbar, call:
require "rack/timeout/rollbar"
> patch up rollbar to group timeouts for the same url

- lib/rack/timeout/core.rb
- lib/rack/timeout/support/assert-types.rb
- lib/rack/timeout/support/namespace.rb
- lib/rack/timeout/support/scheduler.rb
- lib/rack/timeout/support/timeout.rb
this implements #61.
would be great to get testers on it.
> use a single scheduler thread to track all timeouts

- README.markdown
- lib/rack/timeout/core.rb
If `config.action_dispatch.show_exceptions = false` is set and an exception is thrown (not a timeout one), it gets through rack-timeout middleware making hearbeat event logged for failed request forever. E.g.
```
source=rack-timeout id=2842eb4a27a13df8091a0f1aeafb791b timeout=3000ms service=25001ms state=active
source=rack-timeout id=2842eb4a27a13df8091a0f1aeafb791b timeout=3000ms service=26001ms state=active
source=rack-timeout id=2842eb4a27a13df8091a0f1aeafb791b timeout=3000ms service=27001ms state=active
```
This PR ensures all requests are marked as completed on middleware's `call` is completed.
> Ensure state is marked as completed if exception is thrown

- README.markdown
The "The pesky problem of freezing thin servers" article is no longer available at that URL so I removed it. Alternatively, an archived copy of the article can be found here:
https://web.archive.org/web/20130731064820/http://blog.shellycloud.com/2013/06/the-pesky-problem-of-freezing-thin.html?
> Removing broken shellycloud.com link from README

- README.markdown
We mention that `Rack::Timeout::RequestTimeoutException` is the most important, so let's put it at the top.
> Re-organize error list in documentation

- CHANGELOG
To make upgrading easier for people, identify breaking changes
> Docs: In changelog, identify breaking changes

- README.md
This comment was not prepended with a `#`.
> Actually comment the comment

- rack-timeout.gemspec
This PR follows up filename changes on b25cd6d1e37faa90912363b565d4510e2895e730, and adds UPGRADING.md to the gemspec.files.
> Include *.md files in the gem package

- rack-timeout.gemspec
This reduces unnecessary redirection for users who visit here from https://rubygems.org/gems/rack-timeout.
> Update the gemspec's homepage to the current repo URL

- rack-timeout.gemspec
This PR adds rubygems metadata.
https://guides.rubygems.org/specification-reference/#metadata
> gemspec: Add metadata with URLs

- README.md
This PR is a tiny whiny change to the README code example: add a space between hash keys.
> README: Format code example, whitespace [ci skip]

- README.md
- doc/settings.md
- lib/rack/timeout/core.rb
- lib/rack/timeout/logger.rb
- lib/rack/timeout/logging-observer.rb
- lib/rack/timeout/support/monotonic_time.rb
- lib/rack/timeout/support/scheduler.rb
- lib/rack/timeout/support/timeout.rb
- test/env_settings_test.rb
- test/test_helper.rb
When rack-timeout fires then it can put an application in a "bad" state. This is due to https://www.schneems.com/2017/02/21/the-oldest-bug-in-ruby-why-racktimeout-might-hose-your-server/.
We can give applications the option of restarting the entire process when a timeout is hit by sending it a SIGTERM. Why would we want that?
While the `Thread.raise` api is unsafe, restarting a process is safe. If the application is running a multiple-worker webserver such as unicorn or puma, when the worker process gets a SIGTERM then it will be shut down and restarted by the "master" process.
In puma when `SIGTERM` is sent to a worker, that worker will stop accepting new requests, but continue to process all existing requests currently running in threads. This means that sending a SIGTERM to the current …
> [WIP] Allow sending SIGTERM to workers on timeout

- CHANGELOG.md
- doc/settings.md
- lib/rack/timeout/core.rb
The standard convention is that `0` is false in the Rack Timeout config. We don't need to special case this false value. Reverting to prior logic and updating documentation.
> Default of RACK_TIMEOUT_TERM_ON_TIMEOUT to zero

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/rack/timeout/core.rb
- test/env_settings_test.rb
Add Windows to the testing matrix, and exclude tests on Windows for Terminate on Timeout which is not supported on the platform.
Since Windows is a bit more supported now, add a more informative message for the exception.
Fixes #179
> Add tests and improve error messages on Windows

- .github/workflows/ci.yml
- Gemfile
- test/test_helper.rb
This PR adds Ruby 3.2 to the CI matrix.
My original runs failed, because it is necessary to explicitly require `rack` in the `test_helper.rb` when using Rack 3.x.  Since Rack 2.x is still the standard Rack for Rails, and is likely going to be around for a while, I expanded the CI matrix to test against 2.x and 3.x individually.
Everything runs green on my fork.
> Add Ruby 3.2 to CI and test Rack 2/3

- lib/rack/timeout/core.rb
- lib/rack/timeout/logging-observer.rb
Hello, thank you for the incredibly useful library!
I was experimenting with freezing strings in my application by default with `RUBYOPT=--enable=frozen-string-literal`, and `rack-timeout` has a couple places I ran into that are preventing it.
I opted for a minimal changeset as I wasn't sure if there would be openness to freezing strings within the library itself with `# frozen_string_literal: true` (but I'd be happy to include that here too if you'd like).
Error messages I received in testing:
```
can't modify frozen String: "source=rack-timeout" (FrozenError)
can't modify frozen String: "Request " (FrozenError)
```
> ensure mutated strings are mutable

- lib/rack/timeout/support/scheduler.rb
The file is not executed directly, so remove the permission bit.
> Remove unnecessary executable permission bit from Ruby file

- lib/rack-timeout.rb
followup #180
```
dev >> Rails
NameError: uninitialized constant Rails
from (pry):3:in `__pry__'
dev >> require 'web-console'
=> true
dev >> Rails
=> Rails
dev >> Rails::VERSION
NameError: uninitialized constant Rails::VERSION
Did you mean?  Version
from (pry):8:in `__pry__'
dev >> Rails.const_defined?(:VERSION)
=> false
dev >> Rails::VERSION = "3.3.3"
=> "3.3.3"
dev >> Rails.const_defined?(:VERSION)
=> true
```
> Rails no const VERSION (followup #180)

- lib/rack/timeout/core.rb
- test/test_helper.rb
If a process happens to fork from a non-main thread (as happens e.g. in Puma's `fork_worker` mode) the term_on_timeout counter effectively disappears; whichever thread calls `.fork` becomes `Thread.main` in the child process, losing the parent's `Thread.main` storage. There are a few alternative solutions available: make this a real global (makes people feel icky but that's really what the code is doing) or adding a `_fork` hook (only practical on recent Rubies or with ActiveSupport required), but the simplest method is to move the `||= 0` initialization code prior to the request-time code that expects it.
Happy to put up a PR with the alternate methods if you'd prefer, please lmk.
(the `test_helper` change is required for tests to work at all on my local; lots of failures for undefined …
> needed to make this safe for forks from non-main threads

- CHANGELOG.md
- UPGRADING.md
- doc/settings.md
- lib/rack/timeout/core.rb
- test/basic_test.rb
- test/test_helper.rb
At my work we recently switched to nginx from Apache, and were puzzled why we began seeing errors to do with rack-timeout's wait_timeout behavior when we hadn't before.  We'd had the X-Request-Start header set on Apache for some time (years)
I tracked it down to the Apache-formatted header with microseconds, e.g. "t=" + 16 digits like `t=1700173924763384`, not being honored, [as mentioned here](https://github.com/zombocom/rack-timeout/blob/0f35a85a89a8206c2b8a2d1714c39329b3490ce6/lib/rack/timeout/core.rb#L172).
This PR adds that capability, with a test, and also adds notes to docs/settings.md,  UPGRADING.md, and CHANGELOG.md
First commit contains two lines I needed to add to be able to run the project's tests with `rake`.
> Honor Apache X-Request-Start header containing microseconds

- .github/workflows/ci.yml
- README.md
Ruby 2.2 support was removed in https://github.com/zombocom/rack-timeout/commit/30e3f6fc566bc90204154605bf8011b63823d752
> Remove unused exclude for ruby 2.2 in ci.yml
